[package]
org = "sachinira"
name = "github_new_issues_to_gsheet"
version= "0.1.1"

[build-options]
observability-included=true

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.6"


[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.12"